name: Check PR
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  issues: write
  pull-requests: write
  statuses: write

jobs:
  check:
    name: check lint and test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: ./.github/actions/yarn
      - name: run lint
        shell: bash
        run: |
          yarn lint
      - name: run test
        shell: bash
        run: |
          yarn coverage
