name: Check PR
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  issues: write
  pull-requests: write
  statuses: write

jobs:
  check:
    name: check lint and test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v3
      - uses: ./.github/actions/yarn
      - name: run lint
        shell: bash
        run: |
          yarn lint
      - name: run test
        shell: bash
        run: |
          yarn coverage
